<?php
class booking_tour_custom
{
    public $id,$booking_id,$chuong_trinh,$chuong_trinh_price,$thoi_gian,$thoi_gian_price,$nguoi_lon,$tre_em,$tre_em_5,$so_nguoi_price,$khach_san,$khach_san_price,$ngay_khoi_hanh,$ngay_khoi_hanh_price,$hang_bay,$hang_bay_price,$khac,$khac_price,$note;
    public function booking_tour_custom($data=array())
    {
    $this->id=isset($data['id'])?$data['id']:'';
    $this->booking_id=isset($data['booking_id'])?$data['booking_id']:'';
    $this->chuong_trinh=isset($data['chuong_trinh'])?$data['chuong_trinh']:'';
    $this->chuong_trinh_price=isset($data['chuong_trinh_price'])?$data['chuong_trinh_price']:'';
    $this->thoi_gian=isset($data['thoi_gian'])?$data['thoi_gian']:'';
    $this->thoi_gian_price=isset($data['thoi_gian_price'])?$data['thoi_gian_price']:'';
    $this->nguoi_lon=isset($data['nguoi_lon'])?$data['nguoi_lon']:'';
    $this->tre_em=isset($data['tre_em'])?$data['tre_em']:'';
    $this->tre_em_5=isset($data['tre_em_5'])?$data['tre_em_5']:'';
    $this->so_nguoi_price=isset($data['so_nguoi_price'])?$data['so_nguoi_price']:'';
    $this->khach_san=isset($data['khach_san'])?$data['khach_san']:'';
    $this->khach_san_price=isset($data['khach_san_price'])?$data['khach_san_price']:'';
    $this->ngay_khoi_hanh=isset($data['ngay_khoi_hanh'])?$data['ngay_khoi_hanh']:'';
    $this->ngay_khoi_hanh_price=isset($data['ngay_khoi_hanh_price'])?$data['ngay_khoi_hanh_price']:'';
    $this->hang_bay=isset($data['hang_bay'])?$data['hang_bay']:'';
    $this->hang_bay_price=isset($data['hang_bay_price'])?$data['hang_bay_price']:'';
    $this->khac=isset($data['khac'])?$data['khac']:'';
    $this->khac_price=isset($data['khac_price'])?$data['khac_price']:'';
    $this->note=isset($data['note'])?$data['note']:'';
          $this->encode();
    }
    public function encode()
        {
            $this->id=addslashes($this->id);
            $this->booking_id=addslashes($this->booking_id);
            $this->chuong_trinh=addslashes($this->chuong_trinh);
            $this->chuong_trinh_price=addslashes($this->chuong_trinh_price);
            $this->thoi_gian=addslashes($this->thoi_gian);
            $this->thoi_gian_price=addslashes($this->thoi_gian_price);
            $this->nguoi_lon=addslashes($this->nguoi_lon);
            $this->tre_em=addslashes($this->tre_em);
            $this->tre_em_5=addslashes($this->tre_em_5);
            $this->so_nguoi_price=addslashes($this->so_nguoi_price);
            $this->khach_san=addslashes($this->khach_san);
            $this->khach_san_price=addslashes($this->khach_san_price);
            $this->ngay_khoi_hanh=addslashes($this->ngay_khoi_hanh);
            $this->ngay_khoi_hanh_price=addslashes($this->ngay_khoi_hanh_price);
            $this->hang_bay=addslashes($this->hang_bay);
            $this->hang_bay_price=addslashes($this->hang_bay_price);
            $this->khac=addslashes($this->khac);
            $this->khac_price=addslashes($this->khac_price);
            $this->note=addslashes($this->note);
        }
    public function decode()
        {
            $this->id=stripslashes($this->id);
            $this->booking_id=stripslashes($this->booking_id);
            $this->chuong_trinh=stripslashes($this->chuong_trinh);
            $this->chuong_trinh_price=stripslashes($this->chuong_trinh_price);
            $this->thoi_gian=stripslashes($this->thoi_gian);
            $this->thoi_gian_price=stripslashes($this->thoi_gian_price);
            $this->nguoi_lon=stripslashes($this->nguoi_lon);
            $this->tre_em=stripslashes($this->tre_em);
            $this->tre_em_5=stripslashes($this->tre_em_5);
            $this->so_nguoi_price=stripslashes($this->so_nguoi_price);
            $this->khach_san=stripslashes($this->khach_san);
            $this->khach_san_price=stripslashes($this->khach_san_price);
            $this->ngay_khoi_hanh=stripslashes($this->ngay_khoi_hanh);
            $this->ngay_khoi_hanh_price=stripslashes($this->ngay_khoi_hanh_price);
            $this->hang_bay=stripslashes($this->hang_bay);
            $this->hang_bay_price=stripslashes($this->hang_bay_price);
            $this->khac=stripslashes($this->khac);
            $this->khac_price=stripslashes($this->khac_price);
            $this->note=stripslashes($this->note);
        }
}
