<?php
class review_hotel
{
    public $id,$customer_id,$hotel_id,$hotel_name,$hotel_code,$domain,$content,$start_date,$end_date,$status,$clear,$show_clear,$comfort,$show_comfort,$convenient,$show_convenient,$staff,$show_staff,$room,$show_room,$price,$show_price,$food,$show_food,$place,$show_place,$total,$comment,$show_coment,$upcoming_tour,$created,$updated,$updated_by;
    public function review_hotel($data=array())
    {
    $this->id=isset($data['id'])?$data['id']:'';
    $this->customer_id=isset($data['customer_id'])?$data['customer_id']:'';
    $this->hotel_id=isset($data['hotel_id'])?$data['hotel_id']:'';
    $this->hotel_name=isset($data['hotel_name'])?$data['hotel_name']:'';
    $this->hotel_code=isset($data['hotel_code'])?$data['hotel_code']:'';
    $this->domain=isset($data['domain'])?$data['domain']:'';
    $this->content=isset($data['content'])?$data['content']:'';
    $this->start_date=isset($data['start_date'])?$data['start_date']:'';
    $this->end_date=isset($data['end_date'])?$data['end_date']:'';
    $this->status=isset($data['status'])?$data['status']:'';
    $this->clear=isset($data['clear'])?$data['clear']:'';
    $this->show_clear=isset($data['show_clear'])?$data['show_clear']:'';
    $this->comfort=isset($data['comfort'])?$data['comfort']:'';
    $this->show_comfort=isset($data['show_comfort'])?$data['show_comfort']:'';
    $this->convenient=isset($data['convenient'])?$data['convenient']:'';
    $this->show_convenient=isset($data['show_convenient'])?$data['show_convenient']:'';
    $this->staff=isset($data['staff'])?$data['staff']:'';
    $this->show_staff=isset($data['show_staff'])?$data['show_staff']:'';
    $this->room=isset($data['room'])?$data['room']:'';
    $this->show_room=isset($data['show_room'])?$data['show_room']:'';
    $this->price=isset($data['price'])?$data['price']:'';
    $this->show_price=isset($data['show_price'])?$data['show_price']:'';
    $this->food=isset($data['food'])?$data['food']:'';
    $this->show_food=isset($data['show_food'])?$data['show_food']:'';
    $this->place=isset($data['place'])?$data['place']:'';
    $this->show_place=isset($data['show_place'])?$data['show_place']:'';
    $this->total=isset($data['total'])?$data['total']:'';
    $this->comment=isset($data['comment'])?$data['comment']:'';
    $this->show_coment=isset($data['show_coment'])?$data['show_coment']:'';
    $this->upcoming_tour=isset($data['upcoming_tour'])?$data['upcoming_tour']:'';
    $this->created=isset($data['created'])?$data['created']:'';
    $this->updated=isset($data['updated'])?$data['updated']:'';
    $this->updated_by=isset($data['updated_by'])?$data['updated_by']:'';
          $this->encode();
    }
    public function encode()
        {
            $this->id=addslashes($this->id);
            $this->customer_id=addslashes($this->customer_id);
            $this->hotel_id=addslashes($this->hotel_id);
            $this->hotel_name=addslashes($this->hotel_name);
            $this->hotel_code=addslashes($this->hotel_code);
            $this->domain=addslashes($this->domain);
            $this->content=addslashes($this->content);
            $this->start_date=addslashes($this->start_date);
            $this->end_date=addslashes($this->end_date);
            $this->status=addslashes($this->status);
            $this->clear=addslashes($this->clear);
            $this->show_clear=addslashes($this->show_clear);
            $this->comfort=addslashes($this->comfort);
            $this->show_comfort=addslashes($this->show_comfort);
            $this->convenient=addslashes($this->convenient);
            $this->show_convenient=addslashes($this->show_convenient);
            $this->staff=addslashes($this->staff);
            $this->show_staff=addslashes($this->show_staff);
            $this->room=addslashes($this->room);
            $this->show_room=addslashes($this->show_room);
            $this->price=addslashes($this->price);
            $this->show_price=addslashes($this->show_price);
            $this->food=addslashes($this->food);
            $this->show_food=addslashes($this->show_food);
            $this->place=addslashes($this->place);
            $this->show_place=addslashes($this->show_place);
            $this->total=addslashes($this->total);
            $this->comment=addslashes($this->comment);
            $this->show_coment=addslashes($this->show_coment);
            $this->upcoming_tour=addslashes($this->upcoming_tour);
            $this->created=addslashes($this->created);
            $this->updated=addslashes($this->updated);
            $this->updated_by=addslashes($this->updated_by);
        }
    public function decode()
        {
            $this->id=stripslashes($this->id);
            $this->customer_id=stripslashes($this->customer_id);
            $this->hotel_id=stripslashes($this->hotel_id);
            $this->hotel_name=stripslashes($this->hotel_name);
            $this->hotel_code=stripslashes($this->hotel_code);
            $this->domain=stripslashes($this->domain);
            $this->content=stripslashes($this->content);
            $this->start_date=stripslashes($this->start_date);
            $this->end_date=stripslashes($this->end_date);
            $this->status=stripslashes($this->status);
            $this->clear=stripslashes($this->clear);
            $this->show_clear=stripslashes($this->show_clear);
            $this->comfort=stripslashes($this->comfort);
            $this->show_comfort=stripslashes($this->show_comfort);
            $this->convenient=stripslashes($this->convenient);
            $this->show_convenient=stripslashes($this->show_convenient);
            $this->staff=stripslashes($this->staff);
            $this->show_staff=stripslashes($this->show_staff);
            $this->room=stripslashes($this->room);
            $this->show_room=stripslashes($this->show_room);
            $this->price=stripslashes($this->price);
            $this->show_price=stripslashes($this->show_price);
            $this->food=stripslashes($this->food);
            $this->show_food=stripslashes($this->show_food);
            $this->place=stripslashes($this->place);
            $this->show_place=stripslashes($this->show_place);
            $this->total=stripslashes($this->total);
            $this->comment=stripslashes($this->comment);
            $this->show_coment=stripslashes($this->show_coment);
            $this->upcoming_tour=stripslashes($this->upcoming_tour);
            $this->created=stripslashes($this->created);
            $this->updated=stripslashes($this->updated);
            $this->updated_by=stripslashes($this->updated_by);
        }
}
